// Questions
var q = [
    "Hvad forstår du, som andre ikke gør?",
    "Hvorfor vil du få succes?",
    "Hvor stor en mulighed er der?",
    "Hvilke problemer/forhindringer forventer du?",
    "Hvem vil bruge dit produkt?",
    "Hvad koster det at skaffe kunder?",
    "Hvordan vil du tjene penge?",
    "Hvor mange penge kunne du tjene om året?",
    "Hvor mange brugere har du?",
    "Hvad er din bruger-vækstrate?",
    "Hvor mange brugere betaler?",
    "Hvordan møder du kunderne?",
    "Hvordan forstår du kundernes behov?",
    "Hvordan vil du få brugere?",
    "Hvem ville du ansætte, eller hvordan ville du udvide dit team?",
    "Så hvad arbejder du på?",
    "Har du en demo?",
    "Hvor ligger 'raketvidenskaben' her?",
    "Hvordan fungerer dit produkt i detaljer?",
    "Hvordan er dit produkt anderledes?",
    "Hvad er dit næste skridt?",
    "Hvad er nyt ved det, du laver?",
    "Hvad præcis gør dig anderledes end eksisterende løsninger?",
    "Hvem har brug for det, du laver?",
    "Hvordan ved du, at kunderne har brug for det, du laver?",
    "Hvorfor er der ikke nogen, der allerede gør dette?",
    "Hvilke forhindringer vil du møde, og hvordan vil du overvinde dem?",
    "Hvordan vil kunderne finde ud af, at du eksisterer?",
    "Hvilken modstand vil de have mod at prøve dig, og hvordan vil du overvinde den?",
    "Hvad er de vigtigste ting om dit felt, som folk udenfor ikke forstår?",
    "Hvilken del af dit projekt vil du bygge først?",
    "Hvem bliver din første betalende kunde?",
    "Hvis din startup lykkes, hvilke andre områder kunne du så ekspandere til?",
    "Hvorfor valgte du denne idé?",
    "Hvad har du lært indtil videre fra arbejdet med dit produkt?",
    "Om seks måneder, hvad vil være dit største problem?",
    "Hvor kommer nye brugere fra?",
    "Hvordan ser din vækst ud?",
    "Hvad er konverteringsraten?",
    "Hvad får nye brugere til at prøve dig?",
    "Hvorfor holder tilbageholdende brugere sig væk?",
    "Hvad er de vigtigste ting, brugere ønsker?",
    "Hvad har overrasket dig om brugeradfærd?",
    "Hvad er noget imponerende, du har gjort?",
    "Hvad forstår du om dine brugere?",
    "Hvorfor valgte du denne idé at arbejde på?",
    "Hvilken domæneekspertise har du?",
    "Hvem er dine konkurrenter?",
    "Hvem kunne blive konkurrenter?",
    "Nogen viste os en idé som denne lige før jer. Jeg kan ikke lide den. Hvad har I ellers?",
    "Hvilken konkurrence frygter du mest?",
    "Hvad er din distributionsstrategi?",
    "Hvordan mødte jeres team hinanden?",
    "Hvorfor samledes jeres team?",
    "Hvem i jeres team gør hvad?",
    "Hvem er 'chefen'?",
    "Hvad vil du gøre, hvis vi ikke finansierer dig?",
    "Vil du flytte til Silicon Valley?",
    "Hvordan ved vi, at jeres team vil holde sammen?",
    "Hvad har I ellers skabt sammen?",
    "Er du åben for at ændre din idé?",
    "Hvilke systemer har du hacket?",
    "Fortæl os om et svært problem, du har løst?",
    "På hvilke måder er du ressourcefuld?",
    "Vil du genregistrere som et amerikansk selskab?",
    "Vil dit team blive ved dette?",
    "Fortæl os noget overraskende, du har gjort?",
    "Hvad er det sjoveste, der er sket for dig?",
    "Hvad er det værste, der er sket?",
    "Hvad er den største fejl, du har lavet?",
    "Hvad er din burn rate?",
    "Hvor længe kan du klare dig uden finansiering?",
    "Hvad er det næste skridt i produktudviklingen?",
    "Har du rejst finansiering?",
    "Hvem ville være din næste ansættelse?",
    "Hvordan ved du, at folk ønsker dette?",
    "Hvad ved du om dette område/produkt, som andre ikke ved?",
    "Hvordan vil jeres løsning integrere med eksisterende sundhedsplatforme som MinSundhed eller Medicin.dk?",
    "Hvad er de største tekniske udfordringer ved at udvikle jeres AI-modeller, og hvordan adresserer I dem?",
    "Hvordan vil I beskytte jeres løsning mod konkurrenter, der ønsker at kopiere jeres koncept?",
    "Hvordan planlægger I at opnå de nødvendige licenser og overholde GDPR?",
    "Hvordan vil I sikre, at meoo også er anvendeligt for brugere med lav digital kompetence?",
    "Hvordan vil I måle succesen af jeres produkt i de første 12 måneder?",
    "Hvad er jeres strategi for at skalere til internationale markeder?",
    "Hvordan adskiller jeres løsning sig væsentligt fra MinSundhed og lignende offentlige systemer?",
    "Hvordan vil I bruge feedback fra Høreforeningen og andre partnere til at forbedre jeres løsning?",
    "Hvilke sikkerhedsmekanismer implementerer I for at beskytte brugerdata?",
    "Hvordan vil I håndtere potentielle fejl i jeres AI's anbefalinger?",
    "Hvordan sikrer I, at meoo opfylder de forskellige behov hos både patienter og pårørende?",
    "Hvilke marketingkanaler vil I bruge til at introducere meoo for slutbrugerne?",
    "Hvordan vil I opbygge et vedvarende engagement med patientforeninger?",
    "Hvad gør jer overbeviste om, at slutbrugerne vil være villige til at betale for jeres abonnement?",
    "Hvordan planlægger I at rekruttere en co-founder med kommerciel erfaring?",
    "Hvilke risici ser I ved afhængigheden af teknologipartnere som AWS og Azure?",
    "Hvordan tester I brugervenligheden af jeres løsning?",
    "Hvordan kan I dokumentere den værdi, som meoo skaber for sundhedsvæsenet?",
    "Hvad er jeres contingency plan, hvis nogle milestones ikke nås som planlagt?",
    "Hvordan vil I sikre, at sundhedsprofessionelle er positive over for meoo?",
    "Hvordan håndterer I konkurrence fra store tech-virksomheder med mere kapital?",
    "Hvordan vil I sikre, at jeres løsning skaber lige adgang for alle socioøkonomiske grupper?",
    "Hvordan understøtter jeres team samarbejde og hurtig problemløsning?",
    "Hvilke faktorer kunne få jeres primære partnere til at trække sig ud af samarbejdet?",
    "Hvordan vil jeres app hjælpe brugere, der taler andre sprog end dansk?",
    "Hvad er jeres langsigtede vision for meoo?",
    "Hvordan evaluerer I effektiviteten af jeres onboarding-processer?",
    "Hvad er jeres plan for at tiltrække investorer efter Innofounder-forløbet?",
    "Hvordan sikrer I, at meoo til stadighed forbliver innovativ i et konkurrencepræget marked?",
    "Hvordan har i planer om at markedsføre meoo?",
    "I vil finde en co-founder indenfor salg og forretningsudvikling i måned 6. Er det for sent i forløbet når i går efter lancering allerede i måned 9?",
    "Hvordan ser markedet ud?",
    "Har andre bevist, at det kan tjene penge på denne forretningmodel i samme marked?",
    "Tjener jeres konkurrenter penge?",
    "Hvad gør, at i kan komme ind og tage en bid af markedet?",
    "Hvad forhindrer andre i at lave samme løsninig?",
    "I Har allerede fået funding på 150.000 fra Høreforeningen. Hvordan har det bridraget til projektet indtil videre? Og hvorfor er i ikke kommet længere?"
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];