// Questions
var q = [
    "Hvorfor går i efter aftaler med patientforeninger? De har jo ingen penge.",
	"Hvad gør i, hvis en af jer forlader teamet undervejs i forløbet?",
	"Hvad er brugernes problemer, når i snakker med dem?",
	"Hvorfor fungerer jeres team?",
    "Hvad er det innovative ved jer?",
    "Alle kan bruge AI, hvad gør jer unikke?",
	"Hvad er den største udfordring i jeres team?",
	"I siger, at i vil mindske uligheden i sundhedsvæsnet. Hvordan gør i det?",
	"Hvad er det unikke ved jer?",
	"Hvad er det unikke ved jeres teknologi?",
    "Hvad data træner i jeres modeller med?",
    "Hvad er meoo, helt kort fortalt?",
    "Hvad er en RAG-løsning?",
    "Hvad er en AI-agent?",
    "Lad os sige, at jeg lige er blevet diagnosticeret med ADHD, og har downloadet meoo. Hvad skal der så ske?",
    "Hvad forstår du, som andre ikke gør?",
    "Hvorfor vil du få succes?",
    "Hvor stor en mulighed er der?",
    "Hvilke problemer/forhindringer forventer du?",
    "Hvem vil bruge dit produkt?",
    "Hvad koster det at skaffe kunder?",
    "Hvordan vil du tjene penge?",
    "Hvor mange penge kunne du tjene om året?",
    "Hvor mange brugere har du?",
    "Hvad er din bruger-vækstrate?",
    "Hvor mange brugere betaler?",
    "Hvordan møder du kunderne?",
    "Hvordan forstår du kundernes behov?",
    "Hvordan vil du få brugere?",
    "Hvem ville du ansætte, eller hvordan ville du udvide dit team?",
    "Så hvad arbejder du på?",
    "Har du en demo?",
    "Hvor ligger 'raketvidenskaben' her?",
    "Hvordan fungerer dit produkt i detaljer?",
    "Hvordan er dit produkt anderledes?",
    "Hvad er dit næste skridt?",
    "Hvad er nyt ved det, du laver?",
    "Hvad præcis gør dig anderledes end eksisterende løsninger?",
    "Hvem har brug for det, du laver?",
    "Hvordan ved du, at kunderne har brug for det, du laver?",
    "Hvorfor er der ikke nogen, der allerede gør dette?",
    "Hvilke forhindringer vil du møde, og hvordan vil du overvinde dem?",
    "Hvordan vil kunderne finde ud af, at du eksisterer?",
    "Hvilken modstand vil de have mod at prøve dig, og hvordan vil du overvinde den?",
    "Hvad er de vigtigste ting om dit felt, som folk udenfor ikke forstår?",
    "Hvilken del af dit projekt vil du bygge først?",
    "Hvem bliver din første betalende kunde?",
    "Hvis din startup lykkes, hvilke andre områder kunne du så ekspandere til?",
    "Hvorfor valgte du denne idé?",
    "Hvad har du lært indtil videre fra arbejdet med dit produkt?",
    "Om seks måneder, hvad vil være dit største problem?",
    "Hvor kommer nye brugere fra?",
    "Hvordan vil I sikre jer en stærk første lancering, og hvad er planen, hvis adoptionen blandt brugerne går langsommere end forventet?",
    "Hvad gør jeres løsning skalerbar, og hvilke tilpasninger kræves der for at gå fra det danske marked til internationale markeder?",
    "Hvordan vil I indarbejde brugerfeedback fra de første 6 måneder i produktudviklingen?",
    "Hvis jeres AI laver fejl i rådgivningen, hvordan sikrer I, at det ikke underminerer brugerens tillid til meoo?",
    "Hvad er jeres fallback-strategi, hvis teknologipartnere som AWS eller Azure ændrer deres prismodeller markant?",
    "Hvordan ser jeres onboarding-proces for nye brugere ud, og hvordan sikrer I, at brugerne hurtigt ser værdien i meoo?",
    "Hvordan har de 150.000 kr. fra Høreforeningen bidraget til projektet indtil videre, og hvad har I lært fra samarbejdet?",
    "Hvad er jeres plan for at overvinde konkurrence fra potentielle nye spillere, der har mere kapital eller flere ressourcer?",
    "Hvordan balancerer I udviklingen af AI-funktioner med brugervenlighed for personer med lav teknisk erfaring?",
    "Hvordan vil I måle effekten af jeres løsning på brugernes livskvalitet og mentale sundhed?",
    "Hvad er jeres strategi for at håndtere kundernes første indtryk af produktet?",
    "Hvad har I gjort for at sikre, at jeres løsning opfylder kravene for sundheds-IT i Danmark?",
    "Hvordan vil I minimere risikoen for, at brugerdata bliver kompromitteret?",
    "Hvordan kan I skelne jer fra potentielle konkurrenter, der måske kan kopiere jeres løsning hurtigt?",
    "Hvordan vil I demonstrere ROI (Return on Investment) til institutioner som kommuner og patientforeninger?",
    "Hvad er den største udfordring i at skabe en forretningsmodel, der fungerer både for privatpersoner og institutioner?",
    "Hvordan vil I nå ud til patienter i målgrupper, der ikke typisk bruger teknologi som meoo?",
    "Hvordan vil I sikre, at meoo fortsat er relevant i en hurtigt udviklende teknologisk verden?",
    "Hvordan planlægger I at identificere og indgå partnerskaber med flere patientforeninger?",
    "Hvad er den største tekniske udfordring, I står overfor, og hvordan planlægger I at løse den?",
    "Hvordan vil I evaluere succesen af jeres AI-modeller efter lancering?",
    "Hvordan ser jeres milepæle ud i de første 3, 6 og 12 måneder efter Innofounder-forløbet?",
    "Hvad gør jeres team unikt kvalificeret til at løse dette problem?",
    "Hvordan vil I arbejde med branding for at opbygge tillid til meoo som en løsning i sundhedssektoren?",
    "Hvilken rolle spiller jeres advisory board i udviklingen af meoo?",
    "Hvordan sikrer I, at jeres løsning er fleksibel nok til at kunne tilpasses forskellige sundhedssystemer?",
    "Hvordan vil I prioritere mellem forskellige brugerbehov, hvis der opstår konflikter?",
    "Hvilke KPI’er (Key Performance Indicators) vil I bruge til at måle jeres succes?",
    "Hvordan planlægger I at kommunikere kompleksiteten af jeres AI-løsning på en måde, som slutbrugere kan forstå?",
    "Hvad er jeres strategi for at generere positiv omtale og anbefalinger fra tidlige brugere?",
    "Hvordan vil I håndtere situationer, hvor institutionelle kunder ikke ønsker at betale for jeres løsning?",
    "Hvad er de mest kritiske feedbackpunkter, I har modtaget, og hvordan har I reageret på dem?",
    "Hvordan adskiller jeres løsning sig teknologisk fra konkurrenterne?",
    "Hvordan planlægger I at træne jeres AI-modeller yderligere, når antallet af brugere stiger?",
    "Hvordan vil I sikre, at jeres løsning fungerer problemfrit på tværs af forskellige enheder og platforme?",
    "Hvad er jeres forventede tidsramme for at opnå profitabilitet?",
    "Hvordan vil I opbygge og vedligeholde relationer med nøglepartnere i sundhedssektoren?",
    "Hvordan vil I håndtere kulturelle forskelle, når I skal ind på internationale markeder?",
    "Hvad er jeres plan for at rekruttere og integrere nye teammedlemmer, når virksomheden vokser?",
    "Hvordan sikrer I, at jeres løsning også gavner mindre synlige målgrupper, såsom ældre eller handicappede?",
    "Hvordan planlægger I at håndtere negativ feedback eller offentlig kritik af jeres løsning?",
    "Hvad gør jer sikre på, at der er en betalingsvillighed blandt jeres primære målgrupper?",
    "Hvilke alternativer overvejer I, hvis jeres nuværende teknologiske tilgang ikke giver de ønskede resultater?",
    "Hvordan vil I bruge data fra de første brugere til at forbedre produktet?",
    "Hvordan planlægger I at kommunikere jeres værdi til kunder, der ikke er teknisk kyndige?",
    "Hvilken rolle spiller sundhedsinstitutioner i jeres distributionsstrategi?",
    "Hvad er jeres strategi for at håndtere regulatoriske ændringer i sundheds-IT?",
    "Hvordan ser din vækst ud?",
    "Hvad er konverteringsraten?",
    "Hvad får nye brugere til at prøve dig?",
    "Hvorfor holder tilbageholdende brugere sig væk?",
    "Hvad er de vigtigste ting, brugere ønsker?",
    "Hvad har overrasket dig om brugeradfærd?",
    "Hvad er noget imponerende, du har gjort?",
    "Hvad forstår du om dine brugere?",
    "Hvorfor valgte du denne idé at arbejde på?",
    "Hvilken domæneekspertise har du?",
    "Hvem er dine konkurrenter?",
    "Hvem kunne blive konkurrenter?",
    "Nogen viste os en idé som denne lige før jer. Jeg kan ikke lide den. Hvad har I ellers?",
    "Hvilken konkurrence frygter du mest?",
    "Hvad er din distributionsstrategi?",
    "Hvordan mødte jeres team hinanden?",
    "Hvorfor samledes jeres team?",
    "Hvem i jeres team gør hvad?",
    "Hvem er 'chefen'?",
    "Hvad vil du gøre, hvis vi ikke finansierer dig?",
    "Vil du flytte til Silicon Valley?",
    "Hvordan ved vi, at jeres team vil holde sammen?",
    "Hvad har I ellers skabt sammen?",
    "Er du åben for at ændre din idé?",
    "Hvilke systemer har du hacket?",
    "Fortæl os om et svært problem, du har løst?",
    "På hvilke måder er du ressourcefuld?",
    "Vil du genregistrere som et amerikansk selskab?",
    "Vil dit team blive ved dette?",
    "Fortæl os noget overraskende, du har gjort?",
    "Hvad er det sjoveste, der er sket for dig?",
    "Hvad er det værste, der er sket?",
    "Hvad er den største fejl, du har lavet?",
    "Hvad er din burn rate?",
    "Hvor længe kan du klare dig uden finansiering?",
    "Hvad er det næste skridt i produktudviklingen?",
    "Har du rejst finansiering?",
    "Hvem ville være din næste ansættelse?",
    "Hvordan ved du, at folk ønsker dette?",
    "Hvad ved du om dette område/produkt, som andre ikke ved?",
    "Hvordan vil jeres løsning integrere med eksisterende sundhedsplatforme som MinSundhed eller Medicin.dk?",
    "Hvad er de største tekniske udfordringer ved at udvikle jeres AI-modeller, og hvordan adresserer I dem?",
    "Hvordan vil I beskytte jeres løsning mod konkurrenter, der ønsker at kopiere jeres koncept?",
    "Hvordan planlægger I at opnå de nødvendige licenser og overholde GDPR?",
    "Hvordan vil I sikre, at meoo også er anvendeligt for brugere med lav digital kompetence?",
    "Hvordan vil I måle succesen af jeres produkt i de første 12 måneder?",
    "Hvad er jeres strategi for at skalere til internationale markeder?",
    "Hvordan adskiller jeres løsning sig væsentligt fra MinSundhed og lignende offentlige systemer?",
    "Hvordan vil I bruge feedback fra Høreforeningen og andre partnere til at forbedre jeres løsning?",
    "Hvilke sikkerhedsmekanismer implementerer I for at beskytte brugerdata?",
    "Hvordan vil I håndtere potentielle fejl i jeres AI's anbefalinger?",
    "Hvordan sikrer I, at meoo opfylder de forskellige behov hos både patienter og pårørende?",
    "Hvilke marketingkanaler vil I bruge til at introducere meoo for slutbrugerne?",
    "Hvordan vil I opbygge et vedvarende engagement med patientforeninger?",
    "Hvad gør jer overbeviste om, at slutbrugerne vil være villige til at betale for jeres abonnement?",
    "Hvordan planlægger I at rekruttere en co-founder med kommerciel erfaring?",
    "Hvilke risici ser I ved afhængigheden af teknologipartnere som AWS og Azure?",
    "Hvordan tester I brugervenligheden af jeres løsning?",
    "Hvordan kan I dokumentere den værdi, som meoo skaber for sundhedsvæsenet?",
    "Hvad er jeres contingency plan, hvis nogle milestones ikke nås som planlagt?",
    "Hvordan vil I sikre, at sundhedsprofessionelle er positive over for meoo?",
    "Hvordan håndterer I konkurrence fra store tech-virksomheder med mere kapital?",
    "Hvordan vil I sikre, at jeres løsning skaber lige adgang for alle socioøkonomiske grupper?",
    "Hvordan understøtter jeres team samarbejde og hurtig problemløsning?",
    "Hvilke faktorer kunne få jeres primære partnere til at trække sig ud af samarbejdet?",
    "Hvordan vil jeres app hjælpe brugere, der taler andre sprog end dansk?",
    "Hvad er jeres langsigtede vision for meoo?",
    "Hvordan evaluerer I effektiviteten af jeres onboarding-processer?",
    "Hvad er jeres plan for at tiltrække investorer efter Innofounder-forløbet?",
    "Hvordan sikrer I, at meoo til stadighed forbliver innovativ i et konkurrencepræget marked?",
    "Hvordan har i planer om at markedsføre meoo?",
    "I vil finde en co-founder indenfor salg og forretningsudvikling i måned 6. Er det for sent i forløbet når i går efter lancering allerede i måned 9?",
    "Hvordan ser markedet ud?",
    "Har andre bevist, at det kan tjene penge på denne forretningmodel i samme marked?",
    "Tjener jeres konkurrenter penge?",
    "Hvad gør, at i kan komme ind og tage en bid af markedet?",
    "Hvad forhindrer andre i at lave samme løsninig?",
    "I Har allerede fået funding på 150.000 fra Høreforeningen. Hvordan har det bridraget til projektet indtil videre? Og hvorfor er i ikke kommet længere?"
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
